# Generated by Django 6.0.2 on 2026-02-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('core', 'Core'), ('satellite', 'Satellite')], max_length=20)),
                ('domain', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('criticality', models.CharField(choices=[('mission_critical', 'Mission Critical'), ('business_critical', 'Business Critical'), ('business_operational', 'Business Operational'), ('administrative', 'Administrative')], max_length=30)),
                ('lifecycle_status', models.CharField(choices=[('development', 'Development'), ('production', 'Production'), ('phase_out', 'Phase Out'), ('decommissioned', 'Decommissioned')], max_length=20)),
                ('go_live_date', models.DateField(blank=True, null=True)),
                ('planned_decommission_date', models.DateField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('tech_debt', models.TextField(blank=True, null=True)),
                ('tech_debt_severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('env_type', models.CharField(choices=[('DEV', 'Development'), ('UAT', 'User Acceptance Testing'), ('PROD', 'Production')], max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('hosting', models.CharField(choices=[('on-prem', 'On-Premise'), ('cloud', 'Cloud')], max_length=10)),
                ('datacenter', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='app_catalog.application')),
            ],
            options={
                'db_table': 'environments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('API', 'API'), ('message', 'Message'), ('file', 'File')], max_length=10)),
                ('protocol', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('source_to_target', 'Source → Target'), ('target_to_source', 'Target → Source'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('avg_daily_volume', models.IntegerField(blank=True, null=True)),
                ('data_sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('strictly_confidential', 'Strictly Confidential')], max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('external_target', models.CharField(blank=True, max_length=100, null=True)),
                ('source_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations_as_source', to='app_catalog.application')),
                ('target_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations_as_target', to='app_catalog.application')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('business_owner', models.CharField(max_length=100)),
                ('business_owner_department', models.CharField(max_length=100)),
                ('it_owner', models.CharField(max_length=100)),
                ('it_owner_team', models.CharField(max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='app_catalog.application')),
            ],
            options={
                'db_table': 'ownerships',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stack', models.CharField(max_length=100)),
                ('database', models.CharField(blank=True, max_length=100, null=True)),
                ('runtime', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_product', models.CharField(blank=True, max_length=100, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='app_catalog.application')),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'db_table': 'technologies',
                'ordering': ['id'],
            },
        ),
    ]
